#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : poxml
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/poxml-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/poxml-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/poxml-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0
Requires: poxml-bin
Requires: poxml-license
Requires: poxml-man
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : gettext-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package bin
Summary: bin components for the poxml package.
Group: Binaries
Requires: poxml-license
Requires: poxml-man

%description bin
bin components for the poxml package.


%package license
Summary: license components for the poxml package.
Group: Default

%description license
license components for the poxml package.


%package man
Summary: man components for the poxml package.
Group: Default

%description man
man components for the poxml package.


%prep
%setup -q -n poxml-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535238909
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535238909
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/poxml
cp COPYING %{buildroot}/usr/share/doc/poxml/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/poxml/COPYING.DOC
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/poxml/cmake_modules_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/po2xml
/usr/bin/split2po
/usr/bin/swappo
/usr/bin/xml2pot

%files license
%defattr(-,root,root,-)
/usr/share/doc/poxml/COPYING
/usr/share/doc/poxml/COPYING.DOC
/usr/share/doc/poxml/cmake_modules_COPYING-CMAKE-SCRIPTS

%files man
%defattr(-,root,root,-)
/usr/share/man/ca/man1/po2xml.1
/usr/share/man/ca/man1/split2po.1
/usr/share/man/ca/man1/swappo.1
/usr/share/man/ca/man1/xml2pot.1
/usr/share/man/da/man1/po2xml.1
/usr/share/man/da/man1/split2po.1
/usr/share/man/da/man1/swappo.1
/usr/share/man/da/man1/xml2pot.1
/usr/share/man/de/man1/po2xml.1
/usr/share/man/de/man1/split2po.1
/usr/share/man/de/man1/swappo.1
/usr/share/man/de/man1/xml2pot.1
/usr/share/man/es/man1/po2xml.1
/usr/share/man/es/man1/split2po.1
/usr/share/man/es/man1/swappo.1
/usr/share/man/es/man1/xml2pot.1
/usr/share/man/et/man1/split2po.1
/usr/share/man/fr/man1/po2xml.1
/usr/share/man/fr/man1/split2po.1
/usr/share/man/fr/man1/swappo.1
/usr/share/man/fr/man1/xml2pot.1
/usr/share/man/gl/man1/po2xml.1
/usr/share/man/gl/man1/split2po.1
/usr/share/man/gl/man1/swappo.1
/usr/share/man/gl/man1/xml2pot.1
/usr/share/man/it/man1/po2xml.1
/usr/share/man/it/man1/split2po.1
/usr/share/man/it/man1/swappo.1
/usr/share/man/it/man1/xml2pot.1
/usr/share/man/man1/po2xml.1
/usr/share/man/man1/split2po.1
/usr/share/man/man1/swappo.1
/usr/share/man/man1/xml2pot.1
/usr/share/man/nl/man1/po2xml.1
/usr/share/man/nl/man1/split2po.1
/usr/share/man/nl/man1/swappo.1
/usr/share/man/nl/man1/xml2pot.1
/usr/share/man/pt/man1/po2xml.1
/usr/share/man/pt/man1/split2po.1
/usr/share/man/pt/man1/swappo.1
/usr/share/man/pt/man1/xml2pot.1
/usr/share/man/pt_BR/man1/po2xml.1
/usr/share/man/pt_BR/man1/split2po.1
/usr/share/man/pt_BR/man1/swappo.1
/usr/share/man/pt_BR/man1/xml2pot.1
/usr/share/man/ru/man1/po2xml.1
/usr/share/man/ru/man1/split2po.1
/usr/share/man/ru/man1/swappo.1
/usr/share/man/ru/man1/xml2pot.1
/usr/share/man/sv/man1/po2xml.1
/usr/share/man/sv/man1/split2po.1
/usr/share/man/sv/man1/swappo.1
/usr/share/man/sv/man1/xml2pot.1
/usr/share/man/uk/man1/po2xml.1
/usr/share/man/uk/man1/split2po.1
/usr/share/man/uk/man1/swappo.1
/usr/share/man/uk/man1/xml2pot.1
